/// Tradução dos nomes de músculo (`target`/`secondaryMuscles`) que a
/// Biblioteca Oficial de Exercícios (ExerciseDB) usa — 76 valores, entre
/// músculo principal e secundário de todos os 1.394 exercícios — mais os
/// valores adicionais que os 44 exercícios novos da Vital Animations
/// introduziram (nomenclatura mais ampla/por região do corpo em vez de
/// músculo específico; traduzidos de forma consistente com os mesmos
/// termos já usados em `grupos_musculares.dart` pra bodyPart). Usado pra
/// exibir "Peitorais"/"Tríceps" em vez de "pectorals"/"triceps" nas
/// telas de detalhe/execução.
const Map<String, String> musculosLabels = {
  'abdominals': 'Abdominais',
  'abductors': 'Abdutores',
  'abs': 'Abdômen',
  'adductors': 'Adutores',
  'ankle stabilizers': 'Estabilizadores do tornozelo',
  'ankles': 'Tornozelos',
  'back': 'Costas',
  'biceps': 'Bíceps',
  'brachialis': 'Braquial',
  'calves': 'Panturrilhas',
  'cardiovascular system': 'Sistema cardiovascular',
  'chest': 'Peito',
  'core': 'Core',
  'deep cervical flexors': 'Flexores cervicais profundos',
  'deltoids': 'Deltoides',
  'delts': 'Deltoides',
  'extensor digitorum longus': 'Extensor longo dos dedos',
  'extensor hallucis longus': 'Extensor longo do hálux',
  'feet': 'Pés',
  'flexor digitorum longus': 'Flexor longo dos dedos',
  'flexor hallucis longus': 'Flexor longo do hálux',
  'forearms': 'Antebraços',
  'gastrocnemius': 'Gastrocnêmio',
  'gemellus superior/inferior': 'Gêmeos superior/inferior',
  'glutes': 'Glúteos',
  'gluteus medius': 'Glúteo médio',
  'gluteus medius (posterior fibers)': 'Glúteo médio (fibras posteriores)',
  'gluteus minimus': 'Glúteo mínimo',
  'grip muscles': 'Músculos de preensão',
  'groin': 'Virilha',
  'hamstrings': 'Posteriores de coxa',
  'hands': 'Mãos',
  'hip flexors': 'Flexores do quadril',
  'inner thighs': 'Parte interna da coxa',
  'lateral delts': 'Deltoides laterais',
  'latissimus dorsi': 'Grande dorsal',
  'lats': 'Dorsais',
  'levator scapulae': 'Levantador da escápula',
  'longus capitis': 'Longo da cabeça',
  'longus colli': 'Longo do pescoço',
  'lower abs': 'Abdômen inferior',
  'lower arms': 'Antebraços',
  'lower back': 'Lombar',
  'lower legs': 'Panturrilhas',
  'middle traps': 'Trapézio médio',
  'obliques': 'Oblíquos',
  'obturator internus': 'Obturador interno',
  'obturator internus/externus': 'Obturador interno/externo',
  'pectorals': 'Peitorais',
  'peroneus brevis': 'Fibular curto',
  'peroneus longus': 'Fibular longo',
  'peroneus tertius': 'Fibular terceiro',
  'piriformis': 'Piriforme',
  'quadriceps': 'Quadríceps',
  'quads': 'Quadríceps',
  'rear deltoids': 'Deltoides posteriores',
  'rear delts': 'Deltoides posteriores',
  'rhomboids': 'Romboides',
  'rotator cuff': 'Manguito rotador',
  'scalenes': 'Escalenos',
  'semispinalis capitis': 'Semiespinal da cabeça',
  'serratus anterior': 'Serrátil anterior',
  'shins': 'Canelas',
  'shoulders': 'Ombros',
  'soleus': 'Sóleo',
  'spine': 'Coluna',
  'splenius capitis': 'Esplênio da cabeça',
  'splenius cervicis': 'Esplênio do pescoço',
  'sternocleidomastoid': 'Esternocleidomastóideo',
  'suboccipitals': 'Suboccipitais',
  'supraspinatus': 'Supraespinhal',
  'tibialis anterior': 'Tibial anterior',
  'tibialis posterior': 'Tibial posterior',
  'trapezius': 'Trapézio',
  'traps': 'Trapézio',
  'triceps': 'Tríceps',
  'upper arms': 'Braços',
  'upper back': 'Costas superior',
  'upper chest': 'Peito superior',
  'upper legs': 'Pernas',
  'upper trapezius': 'Trapézio superior',
  'upper traps': 'Trapézio superior',
  'wrist extensors': 'Extensores do punho',
  'wrist flexors': 'Flexores do punho',
  'wrists': 'Punhos',
};

String labelMusculo(String valor) {
  return musculosLabels[valor.toLowerCase()] ?? valor;
}
